// Generated by argus_skill.release_tools.generate_manifest. Do not edit.
export const RELEASE_ID = "0.1.1+7f13ee161a09332e";
export const RELEASE_SOURCE_DIGEST = "7f13ee161a09332e2d69692877c0548043a7a4e72be5c146b77382e52fa7dfab";
