// Generated by argus_skill.release_tools.generate_manifest. Do not edit.
export const RELEASE_ID = "0.1.1+23e58451e5302a13";
export const RELEASE_SOURCE_DIGEST = "23e58451e5302a1324adab427440425afa9a08ecbf9bbcb0f31a324db5ffbd61";
