// Generated by argus_skill.release_tools.generate_manifest. Do not edit.
export const RELEASE_ID = "0.1.1+51beeb4774b5a631";
export const RELEASE_SOURCE_DIGEST = "51beeb4774b5a6310962046434d4cfd1db9e287c56912445fe855bac80eabdaf";
